title: Электронный Кабинет Владимира Игоревича Абрамова
permalink: pretty

collections:
  methods:
    output: true
  schoolbook:
    output: true
  fans:
    output: true
  funny:
    output: true

excerpt_separator: <!--more-->
baseurl: abramov/
